[package]
name = "bouncycastle-mldsa"
version = "0.1.2"
edition = "2018"

[workspace]

[features]
default = ["std"]
std = [
    "bouncycastle-mldsa-lowmemory/std",
    "bouncycastle-core-interface/std",
]

[dependencies]
bouncycastle-mldsa-lowmemory = { path = "../mldsa_lowmemory", version = "0.1.2", default-features = false }
bouncycastle-core-interface = { path = "../core-interface", version = "0.1.1", default-features = false }
