[package]
name = "bouncycastle-sha2"
version = "0.1.1"
edition = "2018"

[workspace]

[features]
default = ["std"]
std = ["bouncycastle-core-interface/std", "bouncycastle-utils/std"]

[dependencies]
bouncycastle-core-interface = { path = "../core-interface", version = "0.1.1", default-features = false }
bouncycastle-utils = { path = "../utils", version = "0.1.1", default-features = false }
